import type { Metadata } from "next";
import { Geist, Geist_Mono , Inter , Cairo } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ["latin"] ,
  variable :"--font-inter",
  weight :["400" , "500" ,"600" , "700"]
});
const cairo =Cairo({
  subsets:["arabic"],
  variable :"--font-cairo",
  weight :["400" , "500" ,"600" , "700","1000"]
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <body
        className={`${inter.variable} ${cairo.variable} font-sans`} >
        <ThemeProvider>
           {children}
        </ThemeProvider>
      </body>

    </html>
  );
}
